- hosts: all
  become: true
  vars:
    firewall:
      - { service: [ 'tftp', 'ftp' ],
          port: [ '443/tcp', '443/udp' ],
          trust: [ 'test_eth1', 'test_eth3' ],
          masq: [ 'test_eth2', 'test_eth4' ],
          forward_port: [ 'test_eth0;447/tcp;;1.2.3.4', 'test_eth0;448/tcp;;1.2.3.5' ],
          state: 'enabled' }
      - { service: 'tftp', state: 'enabled' }
      - { port: '443/tcp', state: 'enabled' }
      - { trust: 'test_eth5', state: 'enabled' }
      - { masq: 'test_eth6', state: 'enabled' }
      - { forward_port: 'test_eth0;445/tcp;;1.2.3.4', state: 'enabled' }
  roles:
    - firewall
